"""empty message

Revision ID: 21e0bd385646
Revises: faa6b11d51f1
Create Date: 2020-02-08 15:36:39.476226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e0bd385646'
down_revision = 'faa6b11d51f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'past_shows_count')
    # ### end Alembic commands ###
